config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'welcome#index'
  resources :users
  resources :login
  resources :messages, only: [:create, :destroy, :index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
    
    belongs_to :sender, class_name: 'User'
    has_many :recipients
    has_many :users, :through => :recipients
    
    validates :sender_id, presence: true
    validates :body, presence: true
    
    def user_tokens=(ids)
        self.user_ids = ids
    end
    
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
    belongs_to :message
    belongs_to :user
    
    validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    
  has_many :messages, foreign_key: :sender_id
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def destroy
      session[:user_id] = nil
      redirect_to root_url, :notice => "Logged out!"
    end
    def new
        @user = User.new
    end
    def create
      if user = User.find_by(:email => params[:user][:email]).try(:authenticate, params[:user][:password])
        session[:user_id] = user.id
        redirect_to root_url
      else
        @user = User.new
        flash.now[:error] = 'Email / password is invalid'
        render :new
      end
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    
    def new
        @message = Message.new
        @user = current_user.following
        @user = User.all
    end
    
    def create
        @message = current_user.messages.build(message_params)
        
        if @message.save
            flash[:success] = "Message sent"
            redirect_to root_path
        else
            flash[:alert] = "Fail"
            render :new
        end
    end
    
    def index
        @messages = Recipient.where(:user_id => current_user.id).order("created_at DESC")
    end
    
    def new
        @message = Message.new
        @recipients = User.all
    end
    
    private
        def message_params
            params.require(:message).permit(:body, :content, :title, :thumbnail_url, :sender_id, user_tokens: [])
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end
  
  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @user = User.find_by(id: session[:current_user_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="wrapper">
        
      <header>
          <div class="logo">
              <%= link_to image_tag("http://i.imgur.com/UxE0Ie8.png?1"), root_path %>
          </div>
          <nav>
              <ul>
                  <% if current_user %>
                      <li><a href=""><%= link_to 'INBOX', messages_path %></li>
                      <li><%= link_to 'NEW MESSAGE', new_message_path %></li>
                  <% else %>
                      <li><%= link_to 'SIGN IN', new_login_path %></li>
                      <li><%= link_to 'SIGN UP', new_user_path %></li>
                  <% end %>
              </ul>
          </nav>
      </header>
	<div class="container">
		<% flash.each do |message_type, message| %>
			<div id="flash" class="flash-<%= message_type %>"><%= message %></div>
		<% end %>
        <%= yield %>
	</div>

</body>
</html>

app/views/login/new.html.erb
<div class="form">
    <p><%= image_tag("http://i.imgur.com/GQnJwSG.png?1") %></p>
    <p>LOGIN AND CONTINUE MESSAGING</p>
  <%= form_for @user, {url: '/login', :method => 'post'} do |f| %>
    <%= f.text_field :email,:placeholder => "EMAIL", :class => 'inputText' %>
    <%= f.password_field :password,:placeholder => "PASSWORD", :class => 'inputText' %>
  
    <%= f.submit 'LOGIN', :class => 'inputSubmit' %>
  <% end %>
</div>

app/views/messages/_message.html.erb
<% @messages.each do |message| %>
        <% if message.message.html.present? %>
        <%= message.message.html.html_safe %>
        <% end %>
        <%= message.message.content %>
        <%= link_to message.message.sender.name, message.message.sender %>
<% end %>

app/views/messages/_recipients.html.erb
	<%= form_for :message, url: messages_path do |f| %>
		<%= f.text_area :body,  id: "url", placeholder: "Message", class: "message_body" %>

		<div id="stream-list" class="follow-list">
			<ul>   
				<% @recipients.each do |user| %>
					<label for="user<%= user.id %>" >
						<li id="stream_item">
							<span class="list-group-item"><%= user.email %></span>
							<%= check_box_tag "message[user_tokens][]", user.id, @message.users.include?(user), id: "user#{user.id}" %>
						</li>
					</label>
					<br>
				<% end %>
			</ul>
		</div>

		<div id ="stream-footer">
			<%= f.button :submit, class: "btn btn-outline" %>
		</div>

	<% end %>
</div>

app/views/messages/index.html.erb
		<% @messages.each do |message| %><%= message.message.body %>
					<span>From </span><%= message.message.sender.email %>
		<% end %>

app/views/messages/new.html.erb
		<%= render 'messages/recipients' %>

app/views/users/new.html.erb
<div class="form">
  <p><%= image_tag("http://i.imgur.com/GQnJwSG.png?1") %></p>
  <p>LOGIN AND CONTINUE MESSAGING</p>
  <%= form_for @user do |f| %>
  
    <%= f.text_field :user_name, :placeholder => "USER NAME", :class => 'inputText' %>
    <%= f.text_field :email, :placeholder => "EMAIL", :class => 'inputText' %>
    <%= f.password_field :password, :placeholder => "PASSWORD", :class => 'inputText' %>
    <%= f.password_field :password_confirmation, :placeholder => "PASSWORD CONFIRMATION", :class => 'inputText' %>
  
    <%= f.submit 'SIGN UP', :class => "inputSubmit" %>
  <% end %>
</div>

app/views/welcome/index.html.erb
  
<p class="welcomeImg"><%= image_tag("http://i.imgur.com/cwnanYW.png") %></p>
  <% if current_user %>
    <p class="welcomeEmail"><%= @user.email %></p>
    <%= link_to 'Log out', login_path(@user), :method => :delete %>
  <% end %>